import React, { useState } from 'react';
import { X, Shield, FileText, Mail, HelpCircle, AlertTriangle, Info, Star, Clipboard, Check } from 'lucide-react';

export default function LegalModals({ activeModal, onClose }) {
  const [feedbackType, setFeedbackType] = useState('feature');
  const [feedbackMsg, setFeedbackMsg] = useState('');
  const [rating, setRating] = useState(5);
  const [copied, setCopied] = useState(false);

  const handleSendFeedback = () => {
    const subject = encodeURIComponent(`[ExhibitKIT Feedback] ${feedbackType.toUpperCase()} - Rating: ${rating}/5`);
    const body = encodeURIComponent(
      `Feedback Type: ${feedbackType}\n` +
      `Rating: ${rating}/5\n` +
      `Workstation Signature: EKIT-WORKSTATION-LOCAL-DIAGNOSTICS\n\n` +
      `Feedback Message:\n${feedbackMsg}\n`
    );
    window.location.href = `mailto:support@patentpreppers.com?subject=${subject}&body=${body}`;
  };

  const handleCopyFeedback = () => {
    const text = `Feedback Type: ${feedbackType}\nRating: ${rating}/5\nWorkstation: EKIT-WORKSTATION-LOCAL-DIAGNOSTICS\n\nFeedback Message:\n${feedbackMsg}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!activeModal) return null;

  const renderContent = () => {
    switch (activeModal) {
      case 'terms':
        return (
          <>
            <div className="modal-header-section" style={{ display: 'flex', alignItems: 'center', gap: '12px', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px', marginBottom: '16px' }}>
              <FileText className="modal-icon text-primary" size={24} style={{ color: 'var(--accent-primary)' }} />
              <h3 style={{ fontSize: '20px', fontWeight: '700', margin: 0 }}>Terms of Use</h3>
            </div>
            <div className="modal-scroll-content" style={{ overflowY: 'auto', flex: 1, paddingRight: '8px', display: 'flex', flexDirection: 'column', gap: '16px', fontSize: '13px', lineHeight: '1.6' }}>
              <p className="modal-lead" style={{ fontSize: '14.5px', color: 'var(--text-primary)', fontWeight: '500' }}>Please read these Terms of Use carefully before using ExhibitKIT. By utilizing this software, you agree to these legal conditions.</p>
              
              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>1. No Legal Advice</h4>
                <p style={{ color: 'var(--text-secondary)' }}>ExhibitKIT is a technical document renaming and indexing utility designed for litigation support operations. It does not provide legal advice, legal strategy, or document review. Use of this software does not construct an attorney-client relationship.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>2. Independent Verification Required</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Legal preparation demands absolute precision. The user retains complete responsibility for verifying all outputs, renaming proposals, indexing sequences, and file states generated by this tool prior to courtroom presentations, depositions, filings, or database imports.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>3. Backup Requirement</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Before executing any bulk rename operations (especially in-place directory modifications), users are strictly required to retain comprehensive, separate backup copies of their original documents. PatentPreppers and ExhibitKIT are not responsible for any file corruption, data loss, or overwrites.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>4. Court & Forum Compliance</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Exhibit naming protocols differ substantially by jurisdiction, judge, firm, and trial software platform (e.g., TrialDirector, OnCue). It is the user's sole responsibility to confirm that the chosen configuration satisfies the specifications of their specific legal forum.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>5. Browser Permissions & File Access</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Direct local-first file renaming depends entirely on browser security permissions and native OS file access APIs. Operations are carried out locally on your workstation, and permissions must be explicitly granted by the user.</p>
              </div>
            </div>
          </>
        );

      case 'privacy':
        return (
          <>
            <div className="modal-header-section" style={{ display: 'flex', alignItems: 'center', gap: '12px', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px', marginBottom: '16px' }}>
              <Shield className="modal-icon text-success" size={24} style={{ color: 'var(--status-success)' }} />
              <h3 style={{ fontSize: '20px', fontWeight: '700', margin: 0 }}>Privacy Notice</h3>
            </div>
            <div className="modal-scroll-content" style={{ overflowY: 'auto', flex: 1, paddingRight: '8px', display: 'flex', flexDirection: 'column', gap: '16px', fontSize: '13px', lineHeight: '1.6' }}>
              <p className="modal-lead" style={{ fontSize: '14.5px', color: 'var(--text-primary)', fontWeight: '500' }}>ExhibitKIT is engineered as a local-first application designed for high-stakes, confidential litigation workflows.</p>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>1. Absolute Confidentiality (Offline-First)</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Your litigation documents are highly confidential. ExhibitKIT does NOT upload, transmit, or stream your PDF exhibits or file directories to external servers. All text parsing, sequencing, and renaming operations take place entirely locally within your browser sandbox on your workstation.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>2. Stripe Payment Processing</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Transactions for ExhibitKIT Pro licenses are handled securely by Stripe. ExhibitKIT does not capture, store, or have access to your full credit card information. Stripe provides secure, PCI-compliant payment gateways.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>3. Diagnostics & Support Analytics</h4>
                <p style={{ color: 'var(--text-secondary)' }}>If you submit a support request or email us, we collect only the contact information (name, email) and messages you provide to resolve your inquiry. Workstation tracking is restricted to local identification strings for license seat verification.</p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>4. Future Hosted Features</h4>
                <p style={{ color: 'var(--text-secondary)' }}>Should cloud sync or hosted database connections be introduced in future enterprise tiers, they will require explicit opt-in agreements and will be governed by updated security riders.</p>
              </div>
            </div>
          </>
        );

      case 'support':
        return (
          <>
            <div className="modal-header-section" style={{ display: 'flex', alignItems: 'center', gap: '12px', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px', marginBottom: '16px' }}>
              <Mail className="modal-icon text-info" size={24} style={{ color: '#3b82f6' }} />
              <h3 style={{ fontSize: '20px', fontWeight: '700', margin: 0 }}>Contact Technical Support</h3>
            </div>
            <div className="modal-scroll-content" style={{ overflowY: 'auto', flex: 1, paddingRight: '8px', display: 'flex', flexDirection: 'column', gap: '16px', fontSize: '13px', lineHeight: '1.6' }}>
              <p className="modal-lead" style={{ fontSize: '14.5px', color: 'var(--text-primary)', fontWeight: '500' }}>Need assistance with courtroom-ready renaming, TrialDirector/OnCue presets, or your Pro license?</p>
              
              <div style={{
                background: 'rgba(99, 102, 241, 0.05)',
                border: '1px solid rgba(99, 102, 241, 0.15)',
                borderRadius: '8px',
                padding: '20px',
                textAlign: 'center',
                display: 'flex',
                flexDirection: 'column',
                gap: '8px'
              }}>
                <span style={{ fontSize: '12px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', color: 'var(--text-muted)' }}>
                  PatentPreppers Helpdesk
                </span>
                <a href="mailto:support@patentpreppers.com" style={{ fontSize: '18px', fontWeight: '700', color: 'var(--text-primary)', textDecoration: 'none' }}>
                  support@patentpreppers.com
                </a>
                <p style={{ fontSize: '12px', color: 'var(--text-secondary)', margin: '4px 0 0 0' }}>
                  Litigation support inquiries are processed rapidly. Please include your local Workstation ID and your purchase details for priority support.
                </p>
              </div>

              <div className="legal-block">
                <h4 style={{ color: 'var(--text-primary)', fontWeight: '600', marginBottom: '4px' }}>Enterprise Site Licenses</h4>
                <p style={{ color: 'var(--text-secondary)' }}>
                  For multi-device deployments, automated corporate setups, custom database plugins, or priority firm-wide support SLAs, please contact the licensing desk at our support email above.
                </p>
              </div>
            </div>
          </>
        );

      case 'how':
        return (
          <>
            <div className="modal-header-section" style={{ display: 'flex', alignItems: 'center', gap: '12px', borderBottom: '1px solid var(--border-color)', paddingBottom: '16px', marginBottom: '16px' }}>
              <HelpCircle className="modal-icon text-primary" size={24} style={{ color: 'var(--accent-primary)' }} />
              <h3 style={{ fontSize: '20px', fontWeight: '700', margin: 0 }}>Litigation Guidelines & How to Use</h3>
            </div>
            <div className="modal-scroll-content" style={{ overflowY: 'auto', flex: 1, paddingRight: '8px', display: 'flex', flexDirection: 'column', gap: '20px', fontSize: '13px', lineHeight: '1.6' }}>
              <p className="modal-lead" style={{ fontSize: '14px', color: 'var(--text-primary)', fontWeight: '500' }}>
                Follow this structured operational protocol to ensure your trial databases are fully synchronized, clean, and free of name conflicts.
              </p>

              {/* Strict Disclaimer Header */}
              <div style={{
                background: 'var(--status-danger-bg)',
                border: '1px solid var(--status-danger-border)',
                borderRadius: '8px',
                padding: '16px',
                display: 'flex',
                flexDirection: 'column',
                gap: '8px',
                color: 'var(--status-danger)'
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontWeight: '700', fontSize: '13px' }}>
                  <AlertTriangle size={18} style={{ flexShrink: 0 }} />
                  <span>COURTROOM READINESS & LIABILITY LIMITATION</span>
                </div>
                <p style={{ fontSize: '11.5px', color: 'var(--text-secondary)', lineHeight: '1.5', margin: 0 }}>
                  Litigation operators bear absolute personal liability for verifying the specific numbering guidelines and database constraints required by the local jurisdiction, judicial standing orders, or trial team lead. ExhibitKIT is an offline-safe file-renaming tool; neither <strong>PatentPreppers</strong> nor its developers assume liability for courtroom presentation failures, file corruption, database sync errors, or overwrites.
                </p>
              </div>

              {/* Sorting Constraints & Courtroom Realities */}
              <div style={{
                background: 'rgba(99, 102, 241, 0.04)',
                border: '1px solid rgba(99, 102, 241, 0.1)',
                borderRadius: '8px',
                padding: '14px 16px',
                display: 'flex',
                flexDirection: 'column',
                gap: '8px'
              }}>
                <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', margin: 0 }}>⚖️ Platform Naming Realities & The "PX-10 Before PX-2" Conflict</h5>
                <p style={{ fontSize: '12px', color: 'var(--text-secondary)', lineHeight: '1.5', margin: 0 }}>
                  Computers sort files purely alphabetically. Without zero-padding, a file named <code>PX10</code> is sorted before <code>PX2</code>. ExhibitKIT prevents sorting failures in courtroom presentation software through specific rules:
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', paddingLeft: '8px', borderLeft: '2px solid var(--accent-primary)', marginTop: '4px' }}>
                  <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                    <strong>OnCue Preset (Space-Separated):</strong> No dashes in the exhibit number (e.g., <code>PX001 Contract.pdf</code>). OnCue relies on the first space to parse the Exhibit ID and separate it from the document name.
                  </div>
                  <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                    <strong>TrialDirector Preset (Dash-Separated):</strong> Focuses on rigid dash alignments (e.g., <code>PX-001 - Contract.pdf</code>) to enforce proper database sequencing.
                  </div>
                  <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                    <strong>Zero-Padding Requirement:</strong> Ensure your ID is padded (e.g., <code>001</code> for up to 999 files) so court presentation systems display exhibits in sequential order during live testimony.
                  </div>
                </div>
              </div>

              {/* Steps */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'var(--accent-primary-glow)', color: 'var(--accent-primary)', border: '1px solid var(--border-color-glow)', display: 'flex', alignItems: 'center', justifySelf: 'center', justifyContent: 'center', fontWeight: '700', flexShrink: 0 }}>1</div>
                  <div>
                    <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '4px' }}>Verify Rules & Zero-Padding</h5>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '12px', margin: 0 }}>
                      Set your naming preset (OnCue, TrialDirector, or Custom pattern). Adjust the starting number and digit padding count in the sidebar configuration.
                    </p>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'var(--accent-primary-glow)', color: 'var(--accent-primary)', border: '1px solid var(--border-color-glow)', display: 'flex', alignItems: 'center', justifySelf: 'center', justifyContent: 'center', fontWeight: '700', flexShrink: 0 }}>2</div>
                  <div>
                    <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '4px' }}>Secure Duplicate Backups</h5>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '12px', margin: 0 }}>
                      <strong>Critical Step:</strong> Duplicate your PDF exhibits directory completely. Keep the originals untouched in a secure archive folder. In-place renames are irreversible by the OS.
                    </p>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'var(--accent-primary-glow)', color: 'var(--accent-primary)', border: '1px solid var(--border-color-glow)', display: 'flex', alignItems: 'center', justifySelf: 'center', justifyContent: 'center', fontWeight: '700', flexShrink: 0 }}>3</div>
                  <div>
                    <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '4px' }}>Ingest Target Exhibits</h5>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '12px', margin: 0 }}>
                      Click <strong>Select Local Folder</strong> to pull in exhibits in-place. If using Demo mode, click <strong>Load Sample Exhibits</strong> to work with fake, safe files.
                    </p>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'var(--accent-primary-glow)', color: 'var(--accent-primary)', border: '1px solid var(--border-color-glow)', display: 'flex', alignItems: 'center', justifySelf: 'center', justifyContent: 'center', fontWeight: '700', flexShrink: 0 }}>4</div>
                  <div>
                    <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '4px' }}>Standardize and Clean Up Text</h5>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '12px', margin: 0 }}>
                      Select a casing style, clean special characters/underscores, and hit <strong>Auto-Sequence</strong>. Double-click cells to hand-tune descriptions.
                    </p>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'var(--accent-primary-glow)', color: 'var(--accent-primary)', border: '1px solid var(--border-color-glow)', display: 'flex', alignItems: 'center', justifySelf: 'center', justifyContent: 'center', fontWeight: '700', flexShrink: 0 }}>5</div>
                  <div>
                    <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '4px' }}>Scan & Clear Conflicts</h5>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '12px', margin: 0 }}>
                      Check the Status column. If duplicate numbers are present, resolve them instantly with <strong>Fix Conflicts</strong> to append safe <code>_v2</code> tags automatically.
                    </p>
                  </div>
                </div>

                <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                  <div style={{ width: '24px', height: '24px', borderRadius: '50%', background: 'var(--accent-primary-glow)', color: 'var(--accent-primary)', border: '1px solid var(--border-color-glow)', display: 'flex', alignItems: 'center', justifySelf: 'center', justifyContent: 'center', fontWeight: '700', flexShrink: 0 }}>6</div>
                  <div>
                    <h5 style={{ fontSize: '13.5px', fontWeight: '600', color: 'var(--text-primary)', marginBottom: '4px' }}>Execute & Save Mapping Logs</h5>
                    <p style={{ color: 'var(--text-secondary)', fontSize: '12px', margin: 0 }}>
                      Export a CSV map or HTML audit trail. Hit <strong>Rename PDF Exhibits</strong>, complete the safety backup verification checklist, and execute the renaming batch.
                    </p>
                  </div>
                </div>
              </div>

              {/* Confidentiality banner */}
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
                background: 'rgba(255,255,255,0.02)',
                border: '1px solid rgba(255,255,255,0.05)',
                borderRadius: '6px',
                padding: '10px 14px',
                fontSize: '11px',
                color: 'var(--text-secondary)'
              }}>
                <Info size={14} style={{ flexShrink: 0 }} />
                <span>
                  <strong>Confidential Local Mode:</strong> ExhibitKIT utilizes browser sandbox APIs. Your PDF files and folders are processed on-device. No data or documents are uploaded to cloud servers.
                </span>
              </div>
            </div>
          </>
        );

      case 'feedback':
        return (
          <>
            <div className="modal-header-section" style={{ display: 'flex', alignItems: 'center', gap: '12px', borderBottom: '1px solid rgba(255,255,255,0.05)', paddingBottom: '16px', marginBottom: '16px' }}>
              <Star className="modal-icon text-primary" size={24} style={{ color: 'var(--accent-secondary)' }} />
              <h3 style={{ fontSize: '20px', fontWeight: '700', margin: 0 }}>Submit Professional Feedback</h3>
            </div>
            <div className="modal-scroll-content" style={{ overflowY: 'auto', flex: 1, paddingRight: '8px', display: 'flex', flexDirection: 'column', gap: '16px', fontSize: '13px', lineHeight: '1.6' }}>
              <p style={{ color: 'var(--text-secondary)', fontSize: '13.5px', margin: 0 }}>
                Your feedback directly impacts ExhibitKIT. Share bug reports, suggest custom presets, or recount your courtroom experiences.
              </p>
              
              <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
                <div style={{ flex: 1, minWidth: '140px' }} className="form-group">
                  <label className="form-label">Feedback Category</label>
                  <select 
                    value={feedbackType} 
                    onChange={(e) => setFeedbackType(e.target.value)}
                    style={{ width: '100%', fontSize: '13px', padding: '8px' }}
                  >
                    <option value="feature">✨ Feature Request</option>
                    <option value="bug">🐛 Bug Report</option>
                    <option value="question">❓ General Inquiry</option>
                    <option value="courtroom">⚖️ Courtroom Story</option>
                  </select>
                </div>

                <div style={{ flex: 1, minWidth: '140px' }} className="form-group">
                  <label className="form-label">Overall Experience</label>
                  <div style={{ display: 'flex', gap: '6px', height: '38px', alignItems: 'center' }}>
                    {[1, 2, 3, 4, 5].map((star) => (
                      <Star 
                        key={star}
                        size={20}
                        style={{ cursor: 'pointer', fill: star <= rating ? 'var(--status-warning)' : 'transparent', stroke: star <= rating ? 'var(--status-warning)' : 'var(--text-muted)', transition: 'all 0.15s ease' }}
                        onClick={() => setRating(star)}
                      />
                    ))}
                  </div>
                </div>
              </div>

              <div className="form-group" style={{ marginBottom: 0 }}>
                <label className="form-label">Detailed Notes / Request Details</label>
                <textarea 
                  value={feedbackMsg} 
                  onChange={(e) => setFeedbackMsg(e.target.value)} 
                  placeholder="Tell us what you'd like to see, or report any issues..."
                  rows={4}
                  style={{ width: '100%', background: 'rgba(5, 7, 12, 0.4)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '6px', color: 'var(--text-primary)', padding: '10px', fontSize: '13px', resize: 'vertical' }}
                />
              </div>

              <div style={{ display: 'flex', gap: '10px', marginTop: '8px' }}>
                <button 
                  className="btn btn-primary" 
                  onClick={handleSendFeedback} 
                  disabled={!feedbackMsg.trim()}
                  style={{ flex: 1, opacity: feedbackMsg.trim() ? 1 : 0.5 }}
                >
                  📧 Launch Email Client
                </button>
                
                <button 
                  className="btn btn-secondary" 
                  onClick={handleCopyFeedback}
                  disabled={!feedbackMsg.trim()}
                  style={{ display: 'flex', alignItems: 'center', gap: '6px', opacity: feedbackMsg.trim() ? 1 : 0.5 }}
                >
                  {copied ? <Check size={14} className="text-success" /> : <Clipboard size={14} />}
                  <span>{copied ? 'Copied!' : 'Copy Details'}</span>
                </button>
              </div>

              <div style={{ fontSize: '11px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--bg-tertiary)', padding: '10px', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
                <Shield size={14} className="text-info" />
                <span>Diagnostics: Submitting will include a secure, anonymized workstation signature.</span>
              </div>
            </div>
          </>
        );

      default:
        return null;
    }
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(5, 7, 12, 0.85)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 4000,
      animation: 'slideIn 0.25s cubic-bezier(0.16, 1, 0.3, 1)'
    }}>
      <div className="glass-panel" style={{
        width: '600px',
        maxWidth: '90%',
        maxHeight: '85vh',
        padding: '32px',
        position: 'relative',
        border: '1px solid var(--border-color)',
        boxShadow: 'var(--shadow-lg)',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px'
      }}>
        {/* Close Button */}
        <button 
          onClick={onClose}
          style={{
            position: 'absolute',
            top: '20px',
            right: '20px',
            background: 'transparent',
            border: 'none',
            color: 'var(--text-secondary)',
            cursor: 'pointer',
            padding: '4px',
            zIndex: 10
          }}
        >
          <X size={18} />
        </button>

        {/* Dynamic Modal Content */}
        <div style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' }}>
          {renderContent()}
        </div>

        {/* Footer actions */}
        <div style={{
          display: 'flex',
          justifyContent: 'flex-end',
          paddingTop: '16px',
          borderTop: '1px solid var(--border-color)'
        }}>
          <button className="btn btn-secondary" onClick={onClose} style={{ padding: '8px 16px', fontSize: '13px' }}>
            Close Window
          </button>
        </div>
      </div>
    </div>
  );
}
