import React from 'react';
import { X, Shield, FileText, Mail, HelpCircle } from 'lucide-react';

export default function LegalModals({ activeModal, onClose }) {
  if (!activeModal) return null;

  const renderContent = () => {
    switch (activeModal) {
      case 'terms':
        return (
          <>
            <div className="modal-header-section">
              <FileText className="modal-icon text-primary" size={24} />
              <h3>Terms of Use</h3>
            </div>
            <div className="modal-scroll-content">
              <p className="modal-lead">Please read these Terms of Use carefully before using ExhibitKIT. By utilizing this software, you agree to these legal conditions.</p>
              
              <div className="legal-block">
                <h4>1. No Legal Advice</h4>
                <p>ExhibitKIT is a technical document renaming and indexing utility designed for litigation support operations. It does not provide legal advice, legal strategy, or document review. Use of this software does not construct an attorney-client relationship.</p>
              </div>

              <div className="legal-block">
                <h4>2. Independent Verification Required</h4>
                <p>Legal preparation demands absolute precision. The user retains complete responsibility for verifying all outputs, renaming proposals, indexing sequences, and file states generated by this tool prior to courtroom presentations, depositions, filings, or database imports.</p>
              </div>

              <div className="legal-block">
                <h4>3. Backup Requirement</h4>
                <p>Before executing any bulk rename operations (especially in-place directory modifications), users are strictly required to retain comprehensive, separate backup copies of their original documents. ExhibitKIT is not responsible for any file corruption, data loss, or overwrites.</p>
              </div>

              <div className="legal-block">
                <h4>4. Court & Forum Compliance</h4>
                <p>Exhibit naming protocols differ substantially by jurisdiction, judge, firm, and trial software platform (e.g., TrialDirector, OnCue). It is the user's sole responsibility to confirm that the chosen configuration satisfies the specifications of their specific legal forum.</p>
              </div>

              <div className="legal-block">
                <h4>5. Browser Permissions & File Access</h4>
                <p>Direct local-first file renaming depends entirely on browser security permissions and native OS file access APIs. Operations are carried out locally on your workstation, and permissions must be explicitly granted by the user.</p>
              </div>
            </div>
          </>
        );

      case 'privacy':
        return (
          <>
            <div className="modal-header-section">
              <Shield className="modal-icon text-success" size={24} />
              <h3>Privacy Notice</h3>
            </div>
            <div className="modal-scroll-content">
              <p className="modal-lead">ExhibitKIT is engineered as a local-first application designed for high-stakes, confidential litigation workflows.</p>

              <div className="legal-block">
                <h4>1. Absolute Confidentiality (Offline-First)</h4>
                <p>Your litigation documents are highly confidential. ExhibitKIT does NOT upload, transmit, or stream your PDF exhibits or file directories to external servers. All text parsing, sequencing, and renaming operations take place entirely locally within your browser sandbox on your workstation.</p>
              </div>

              <div className="legal-block">
                <h4>2. Stripe Payment Processing</h4>
                <p>Transactions for ExhibitKIT Pro licenses are handled securely by Stripe. ExhibitKIT does not capture, store, or have access to your full credit card information. Stripe provides secure, PCI-compliant payment gateways.</p>
              </div>

              <div className="legal-block">
                <h4>3. Diagnostics & Support Analytics</h4>
                <p>If you submit a support request or email us, we collect only the contact information (name, email) and messages you provide to resolve your inquiry. Workstation tracking is restricted to local identification strings for license seat verification.</p>
              </div>

              <div className="legal-block">
                <h4>4. Future Cloud Services</h4>
                <p>Should cloud sync or hosted database connections be introduced in future enterprise tiers, they will require explicit opt-in agreements and will be governed by updated security riders.</p>
              </div>
            </div>
          </>
        );

      case 'support':
        return (
          <>
            <div className="modal-header-section">
              <Mail className="modal-icon text-info" size={24} />
              <h3>Contact Technical Support</h3>
            </div>
            <div className="modal-scroll-content">
              <p className="modal-lead">Need assistance with courtroom-ready renaming, TrialDirector/OnCue presets, or your Pro license?</p>
              
              <div className="support-card">
                <p><strong>Primary Support Email:</strong></p>
                <a href="mailto:support@exhibitkit.app" className="support-email">support@exhibitkit.app</a>
                <p className="support-note">Litigation support inquiries are processed on business days. Please include your Workstation ID and license transaction email for rapid diagnostic support.</p>
              </div>

              <div className="legal-block">
                <h4>Enterprise Deployments</h4>
                <p>For firm-wide deployments, administrative workstations, custom server configurations, or site licensing agreements, please contact the operations desk directly at our support email.</p>
              </div>
            </div>
          </>
        );

      case 'how':
        return (
          <>
            <div className="modal-header-section">
              <HelpCircle className="modal-icon text-primary" size={24} />
              <h3>How to Use ExhibitKIT</h3>
            </div>
            <div className="modal-scroll-content">
              <p className="modal-lead">Follow this structured checklist to ensure your legal exhibits are perfectly indexed and formatted for TrialDirector or OnCue.</p>

              <div className="step-list">
                <div className="step-item">
                  <div className="step-num">1</div>
                  <div className="step-text">
                    <strong>Select Naming Preset:</strong>
                    Choose <strong>OnCue</strong> (space-separated, e.g., <code>PX001 Memo</code>) or <strong>TrialDirector</strong> (hyphenated, e.g., <code>PX-001 - Memo</code>) based on your target trial platform.
                  </div>
                </div>

                <div className="step-item">
                  <div className="step-num">2</div>
                  <div className="step-text">
                    <strong>Load Files:</strong>
                    Use **Load Sample Exhibits** in Demo mode to test the configuration, or load real PDFs using **Select Local Folder** (Trial/Pro) for direct in-place local disk renaming.
                  </div>
                </div>

                <div className="step-item">
                  <div className="step-num">3</div>
                  <div className="step-text">
                    <strong>Review & Sequence:</strong>
                    Review the exhibit IDs and description columns. Use the **Auto-Sequence** button to rapidly index documents from your desired start number. Double-click or select fields to manually override IDs or descriptions.
                  </div>
                </div>

                <div className="step-item">
                  <div className="step-num">4</div>
                  <div className="step-text">
                    <strong>Scan & Fix Conflicts:</strong>
                    If you see duplicate filenames or naming warnings, click the **Fix Conflicts** button to automatically append sequence markers (e.g. <code>_v2</code>) and ensure clean imports.
                  </div>
                </div>

                <div className="step-item">
                  <div className="step-num">5</div>
                  <div className="step-text">
                    <strong>Export Audit Reports:</strong>
                    Download the mapping layout using **Export CSV Mapping** or generate a gorgeous printable audit trail from the Action Panel before running renames.
                  </div>
                </div>

                <div className="step-item">
                  <div className="step-num">6</div>
                  <div className="step-text">
                    <strong>Verify Backups & Rename:</strong>
                    Confirm you have secure duplicates of your original exhibits. Review the final proposed grid carefully, tick the backup checklist, and execute the in-place rename.
                  </div>
                </div>
              </div>
            </div>
          </>
        );

      default:
        return null;
    }
  };

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(5, 7, 12, 0.85)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2000,
      animation: 'slideIn 0.25s cubic-bezier(0.16, 1, 0.3, 1)'
    }}>
      <div className="glass-panel" style={{
        width: '600px',
        maxWidth: '90%',
        maxHeight: '85vh',
        padding: '32px',
        position: 'relative',
        border: '1px solid rgba(255, 255, 255, 0.08)',
        boxShadow: 'var(--shadow-lg)',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px'
      }}>
        {/* Close Button */}
        <button 
          onClick={onClose}
          style={{
            position: 'absolute',
            top: '20px',
            right: '20px',
            background: 'transparent',
            border: 'none',
            color: 'var(--text-secondary)',
            cursor: 'pointer',
            padding: '4px',
            zIndex: 10
          }}
        >
          <X size={18} />
        </button>

        {/* Dynamic Modal Content */}
        <div style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' }}>
          {renderContent()}
        </div>

        {/* Footer actions */}
        <div style={{
          display: 'flex',
          justifyContent: 'flex-end',
          paddingTop: '16px',
          borderTop: '1px solid rgba(255, 255, 255, 0.05)'
        }}>
          <button className="btn btn-secondary" onClick={onClose} style={{ padding: '8px 16px', fontSize: '13px' }}>
            Close Window
          </button>
        </div>
      </div>
    </div>
  );
}
